"""delete test column

Revision ID: 20efe6906cd8
Revises: a430fa18a8df
Create Date: 2023-08-29 20:23:01.507471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20efe6906cd8'
down_revision: Union[str, None] = 'a430fa18a8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'author_contacts', ['uid'])
    op.create_unique_constraint(None, 'authors', ['uid'])
    op.create_unique_constraint(None, 'content', ['uid'])
    op.drop_column('content', 'test')
    op.create_unique_constraint(None, 'publications', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publications', type_='unique')
    op.add_column('content', sa.Column('test', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'content', type_='unique')
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_constraint(None, 'author_contacts', type_='unique')
    # ### end Alembic commands ###
