"""drop_clmn

Revision ID: 7c0094b16926
Revises: 975a98b2a2db
Create Date: 2023-08-29 20:20:39.609880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0094b16926'
down_revision: Union[str, None] = '975a98b2a2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('author_contacts_value_key', 'author_contacts', type_='unique')
    op.create_unique_constraint(None, 'author_contacts', ['uid'])
    op.drop_column('author_contacts', 'value')
    op.create_unique_constraint(None, 'authors', ['uid'])
    op.create_unique_constraint(None, 'content', ['uid'])
    op.create_unique_constraint(None, 'publications', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publications', type_='unique')
    op.drop_constraint(None, 'content', type_='unique')
    op.drop_constraint(None, 'authors', type_='unique')
    op.add_column('author_contacts', sa.Column('value', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'author_contacts', type_='unique')
    op.create_unique_constraint('author_contacts_value_key', 'author_contacts', ['value'])
    # ### end Alembic commands ###
