"""add_text

Revision ID: a430fa18a8df
Revises: 7c0094b16926
Create Date: 2023-08-29 20:22:04.184782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a430fa18a8df'
down_revision: Union[str, None] = '7c0094b16926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('test', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'test')
    # ### end Alembic commands ###
